# Generated by Django 5.2.6 on 2025-09-20 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_commission_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Pourcentage de commission des formateurs')),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Pourcentage de frais de transaction')),
                ('minimum_payment_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum de paiement')),
                ('maximum_payment_amount', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant maximum de paiement')),
                ('stripe_enabled', models.BooleanField(default=True, verbose_name='Stripe activé')),
                ('orange_money_enabled', models.BooleanField(default=True, verbose_name='Orange Money activé')),
                ('free_money_enabled', models.BooleanField(default=True, verbose_name='Free Money activé')),
                ('mtn_money_enabled', models.BooleanField(default=True, verbose_name='MTN Money activé')),
                ('webhook_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name='Secret des webhooks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Configuration des paiements',
                'verbose_name_plural': 'Configurations des paiements',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('payment_type', models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('mtn_money', 'MTN Money'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces')], max_length=20, verbose_name='Type de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('mtn_money', 'MTN Money')], max_length=20, verbose_name='Fournisseur')),
                ('event_type', models.CharField(max_length=100, verbose_name="Type d'événement")),
                ('event_id', models.CharField(max_length=100, unique=True, verbose_name="ID de l'événement")),
                ('payload', models.JSONField(verbose_name='Données reçues')),
                ('processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
            ],
            options={
                'verbose_name': 'Webhook de paiement',
                'verbose_name_plural': 'Webhooks de paiement',
            },
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course', verbose_name='Cours')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='courses.enrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Paiement de cours',
                'verbose_name_plural': 'Paiements de cours',
            },
        ),
        migrations.CreateModel(
            name='InstructorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la commission')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Pourcentage de commission')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('course_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.coursepayment', verbose_name='Paiement de cours')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Commission de formateur',
                'verbose_name_plural': 'Commissions de formateurs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('external_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de paiement externe')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentmethod', verbose_name='Méthode de paiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_payment', to='payments.payment', verbose_name='Paiement'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du remboursement')),
                ('reason', models.TextField(verbose_name='Raison du remboursement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('external_refund_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de remboursement externe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
            },
        ),
    ]
