# Generated by Django 5.2.6 on 2025-09-21 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField(verbose_name='ID du cours')),
                ('course_title', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause'), ('completed', 'Terminé'), ('dropped', 'Abandonné')], default='active', max_length=20, verbose_name='Statut')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Dernier accès')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de progression')),
                ('total_time_spent', models.PositiveIntegerField(default=0, verbose_name='Temps total (minutes)')),
                ('current_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Note actuelle')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificat émis')),
                ('certificate_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du certificat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription au cours',
                'verbose_name_plural': 'Inscriptions aux cours',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Série actuelle')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Plus longue série')),
                ('last_activity_date', models.DateField(auto_now_add=True, verbose_name='Dernière activité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Série d'apprentissage",
                'verbose_name_plural': "Séries d'apprentissage",
                'ordering': ['-current_streak'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.PositiveIntegerField(verbose_name='ID de la leçon')),
                ('lesson_title', models.CharField(max_length=200, verbose_name='Titre de la leçon')),
                ('lesson_type', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Texte'), ('quiz', 'Quiz'), ('document', 'Document'), ('interactive', 'Interactif')], default='text', max_length=20, verbose_name='Type de leçon')),
                ('lesson_order', models.PositiveIntegerField(default=1, verbose_name='Ordre de la leçon')),
                ('estimated_duration', models.PositiveIntegerField(default=0, verbose_name='Durée estimée (minutes)')),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('skipped', 'Ignoré')], default='not_started', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Dernier accès')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progression (%)')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Temps passé (minutes)')),
                ('current_position', models.PositiveIntegerField(default=0, verbose_name='Position actuelle')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.courseenrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Progression de la leçon',
                'verbose_name_plural': 'Progressions des leçons',
                'ordering': ['lesson_order'],
                'unique_together': {('enrollment', 'lesson_id')},
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('course_completion', 'Fin de cours')], max_length=20, verbose_name='Type de rapport')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('courses_enrolled', models.PositiveIntegerField(default=0, verbose_name='Cours inscrits')),
                ('courses_completed', models.PositiveIntegerField(default=0, verbose_name='Cours terminés')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Leçons terminées')),
                ('total_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Temps total (minutes)')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score moyen')),
                ('detailed_data', models.JSONField(default=dict, verbose_name='Données détaillées')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rapport de progression',
                'verbose_name_plural': 'Rapports de progression',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField(verbose_name='ID du cours')),
                ('course_title', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('lesson_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la leçon')),
                ('lesson_title', models.CharField(blank=True, max_length=200, verbose_name='Titre de la leçon')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Début')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('lessons_viewed', models.PositiveIntegerField(default=0, verbose_name='Leçons vues')),
                ('quizzes_attempted', models.PositiveIntegerField(default=0, verbose_name='Quiz tentés')),
                ('active_time_minutes', models.PositiveIntegerField(default=0, verbose_name='Temps actif (minutes)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Session d'étude",
                'verbose_name_plural': "Sessions d'étude",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('course_completion', 'Cours terminé'), ('quiz_master', 'Maître du quiz'), ('streak', "Série d'étude"), ('time_spent', 'Temps passé'), ('perfect_score', 'Score parfait'), ('fast_learner', 'Apprenant rapide'), ('consistent', 'Régularité')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Obtenu le')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('course_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du cours')),
                ('lesson_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la leçon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.PositiveIntegerField(verbose_name='ID du module')),
                ('module_title', models.CharField(max_length=200, verbose_name='Titre du module')),
                ('module_order', models.PositiveIntegerField(default=1, verbose_name='Ordre du module')),
                ('is_started', models.BooleanField(default=False, verbose_name='Commencé')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progression (%)')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Temps passé (minutes)')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.courseenrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Progression du module',
                'verbose_name_plural': 'Progressions des modules',
                'ordering': ['module_order'],
                'unique_together': {('enrollment', 'module_id')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.PositiveIntegerField(verbose_name='ID du quiz')),
                ('quiz_title', models.CharField(max_length=200, verbose_name='Titre du quiz')),
                ('quiz_passing_score', models.DecimalField(decimal_places=2, default=70, max_digits=5, verbose_name='Score minimum')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Numéro de tentative')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Débuté à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score (%)')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Total questions')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Bonnes réponses')),
                ('time_taken', models.PositiveIntegerField(verbose_name='Temps pris (secondes)')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.lessonprogress', verbose_name='Progression leçon')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-started_at'],
                'unique_together': {('lesson_progress', 'quiz_id', 'attempt_number')},
            },
        ),
    ]
