# Generated by Django 5.2.6 on 2025-09-20 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur')),
                ('badge_type', models.CharField(choices=[('completion', 'Completion'), ('achievement', 'Achievement'), ('milestone', 'Milestone'), ('special', 'Special')], default='achievement', max_length=20, verbose_name='Type de badge')),
                ('criteria', models.JSONField(default=dict, verbose_name="Critères d'obtention")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('certificate_type', models.CharField(choices=[('course_completion', 'Completion de cours'), ('skill_verification', 'Vérification de compétence'), ('professional', 'Certificat professionnel'), ('participation', 'Certificat de participation')], default='course_completion', max_length=30, verbose_name='Type de certificat')),
                ('template', models.TextField(verbose_name='Template HTML')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='certificates/backgrounds/', verbose_name='Image de fond')),
                ('requirements', models.JSONField(default=dict, verbose_name='Exigences')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('duration_weeks', models.PositiveIntegerField(default=0, verbose_name='Durée (semaines)')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20, verbose_name='Niveau de difficulté')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='learning_paths/thumbnails/', verbose_name='Miniature')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': "Parcours d'apprentissage",
                'verbose_name_plural': "Parcours d'apprentissage",
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('course_completed', 'Cours terminé'), ('learning_path_completed', 'Parcours terminé'), ('certificate_earned', 'Certificat obtenu'), ('badge_earned', 'Badge obtenu'), ('quiz_passed', 'Quiz réussi'), ('streak', 'Série de connexions'), ('time_spent', 'Temps passé')], max_length=30, verbose_name='Type de réalisation')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('data', models.JSONField(default=dict, verbose_name='Données')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'obtention")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Débuté à')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('progress_made', models.JSONField(default=dict, verbose_name='Progression effectuée')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.course', verbose_name='Cours')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.lesson', verbose_name='Leçon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Session d'étude",
                'verbose_name_plural': "Sessions d'étude",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses_enrolled', models.PositiveIntegerField(default=0, verbose_name='Cours inscrits')),
                ('total_courses_completed', models.PositiveIntegerField(default=0, verbose_name='Cours terminés')),
                ('total_lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Leçons terminées')),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0, verbose_name='Temps total passé (minutes)')),
                ('current_streak_days', models.PositiveIntegerField(default=0, verbose_name='Série actuelle (jours)')),
                ('longest_streak_days', models.PositiveIntegerField(default=0, verbose_name='Plus longue série (jours)')),
                ('total_certificates_earned', models.PositiveIntegerField(default=0, verbose_name='Certificats obtenus')),
                ('total_badges_earned', models.PositiveIntegerField(default=0, verbose_name='Badges obtenus')),
                ('total_quizzes_taken', models.PositiveIntegerField(default=0, verbose_name='Quiz passés')),
                ('total_quizzes_passed', models.PositiveIntegerField(default=0, verbose_name='Quiz réussis')),
                ('average_quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score moyen des quiz')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Statistiques utilisateur',
                'verbose_name_plural': 'Statistiques utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='courses.course', verbose_name='Cours')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='progress.learningpath', verbose_name="Parcours d'apprentissage")),
            ],
            options={
                'verbose_name': 'Cours de parcours',
                'verbose_name_plural': 'Cours de parcours',
                'ordering': ['order'],
                'unique_together': {('learning_path', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'obtention")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='progress.badge', verbose_name='Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Badge utilisateur',
                'verbose_name_plural': 'Badges utilisateurs',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('certificate_data', models.JSONField(default=dict, verbose_name='Données du certificat')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/', verbose_name='Fichier PDF')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('verification_code', models.CharField(max_length=20, unique=True, verbose_name='Code de vérification')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='progress.certificate', verbose_name='Certificat')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates_issued', to='courses.course', verbose_name='Cours')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_issued', to=settings.AUTH_USER_MODEL, verbose_name='Émis par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Certificat utilisateur',
                'verbose_name_plural': 'Certificats utilisateurs',
                'unique_together': {('user', 'certificate', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de progression')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='progress.learningpath', verbose_name="Parcours d'apprentissage")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Parcours utilisateur',
                'verbose_name_plural': 'Parcours utilisateurs',
                'unique_together': {('user', 'learning_path')},
            },
        ),
    ]
