# Generated by Django 5.2.6 on 2025-09-20 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe (hash)')),
                ('message', models.TextField(verbose_name='Message')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='User agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('honeypot', models.CharField(blank=True, max_length=255, null=True, verbose_name='Honeypot (anti-spam)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
