# Generated by Django 5.2.6 on 2025-09-20 21:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Apprenant'), ('instructor', 'Formateur'), ('admin', 'Administrateur'), ('enterprise', 'Entreprise')], default='student', max_length=20, verbose_name='Rôle')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, null=True, verbose_name='Genre')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue préférée')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('company_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'entreprise")),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité")),
                ('company_size', models.CharField(blank=True, max_length=20, null=True, verbose_name="Taille de l'entreprise")),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Personne de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_profile', to=settings.AUTH_USER_MODEL, verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Profil entreprise',
                'verbose_name_plural': 'Profils entreprises',
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre professionnel')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('specializations', models.JSONField(blank=True, default=list, verbose_name='Spécialisations')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif horaire (FCFA)')),
                ('availability', models.JSONField(blank=True, default=dict, verbose_name='Disponibilité')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Profil formateur',
                'verbose_name_plural': 'Profils formateurs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Compétences')),
                ('experience', models.JSONField(blank=True, default=list, verbose_name='Expérience')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='Formation')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='Certifications')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Liens sociaux')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, verbose_name='Préférences de notification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
