# Generated by Django 5.2.6 on 2025-09-20 21:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(max_length=500, verbose_name='Description courte')),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20, verbose_name='Niveau')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('wo', 'Wolof'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Miniature')),
                ('video_intro', models.URLField(blank=True, null=True, verbose_name="Vidéo d'introduction")),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Durée (heures)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Certifié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Catégorie')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Module de cours',
                'verbose_name_plural': 'Modules de cours',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('lesson_type', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Texte'), ('quiz', 'Quiz'), ('assignment', 'Devoir'), ('live', 'Classe virtuelle')], default='video', max_length=20, verbose_name='Type de leçon')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL vidéo')),
                ('video_duration', models.PositiveIntegerField(default=0, verbose_name='Durée vidéo (minutes)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='courses/attachments/', verbose_name='Fichier joint')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('time_limit', models.PositiveIntegerField(default=0, verbose_name='Limite de temps (minutes)')),
                ('passing_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de passage (%)')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Nombre maximum de tentatives')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='Pourcentage')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Débuté à')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé à')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='Temps pris (minutes)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Choix multiple'), ('true_false', 'Vrai/Faux'), ('text', 'Texte libre')], default='multiple_choice', max_length=20, verbose_name='Type de question')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question de quiz',
                'verbose_name_plural': 'Questions de quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse de quiz',
                'verbose_name_plural': 'Réponses de quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Cours')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Avis de cours',
                'verbose_name_plural': 'Avis de cours',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de progression')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Cours')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Temps passé (minutes)')),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='Dernière position (secondes)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='Leçon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Progression de leçon',
                'verbose_name_plural': 'Progressions de leçons',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
